import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {client,signIn} from './oidc-session.mjs';
const fixture=JSON.parse(readFileSync(new URL('../../infrastructure/local/generated/demo-ids.json',import.meta.url)));
const api={};for(const name of ['requester','manager','finance','outsider'])api[name]=client(await signIn(name));
const tenant=`/tenants/${fixture.acmeId}`,base=tenant+'/cases';
const purchase={vendor:'Synthetic <Tools> & Co',description:'Document pipeline laptop',currency:'USD',costCenter:'TRAINING',justification:'Synthetic end-to-end document test',lineItems:[{description:'Laptop',quantity:'1',unitPrice:'4200.00'}]};
let item=await api.requester(base,{method:'POST',body:{purchase,workflowId:fixture.workflowId,templateId:fixture.templateId}});
const path=base+'/'+item.id;
item=await api.requester(path+'/assignments',{method:'PUT',body:{expectedVersion:item.version,approverIds:[fixture.users.manager,fixture.users.finance]}});
item=await api.requester(path+'/start',{method:'POST',body:{expectedVersion:item.version}});
assert.equal(item.templateId,fixture.templateId);
item=await api.manager(path+'/actions',{method:'POST',body:{expectedVersion:item.version,action:'APPROVE'}});
item=await api.finance(path+'/actions',{method:'POST',body:{expectedVersion:item.version,action:'APPROVE'}});
assert.equal(item.state,'APPROVED');
let job=(await api.requester(path+'/documents')).items[0];
const observed=new Set([job.status]);
const deadline=Date.now()+60000;
while(job.status!=='SUCCEEDED'&&Date.now()<deadline){
  assert.notEqual(job.status,'FAILED',`Document failed: ${job.failureCode}`);
  await new Promise(resolve=>setTimeout(resolve,500));
  job=await api.requester(`${tenant}/jobs/${job.jobId}`);observed.add(job.status);
}
assert.equal(job.status,'SUCCEEDED');
await api.outsider(path+`/documents/${job.jobId}/download-url`,{method:'POST',expected:404});
await api.requester(`${tenant}/jobs/${job.jobId}/retry`,{method:'POST',body:{expectedAttempt:job.attempt},expected:403});
const download=await api.requester(path+`/documents/${job.jobId}/download-url`,{method:'POST'});
assert.equal(download.expiresInSeconds,60);
const response=await fetch(download.url);assert.equal(response.status,200);
const bytes=Buffer.from(await response.arrayBuffer());
assert.equal(createHash('sha256').update(bytes).digest('hex'),job.sha256);
assert.equal(bytes.length,job.byteSize);
const output=fileURLToPath(new URL('../../infrastructure/local/generated/document-smoke.docx',import.meta.url));
writeFileSync(output,bytes);
const python=fileURLToPath(new URL('../../services/worker/.venv/Scripts/python.exe',import.meta.url));
execFileSync(python,['-c',"import sys; from docx import Document; text='\\n'.join(p.text for p in Document(sys.argv[1]).paragraphs); assert 'Synthetic <Tools> & Co' in text; assert '4200.00' in text; assert '{{' not in text",output]);
const final=await api.requester(path);assert.equal(final.state,'APPROVED');assert.equal(final.documentStatus,'SUCCEEDED');
console.log('PASS real approval -> Java outbox -> Kafka -> Python DOCX -> worker outbox -> Java completion');
console.log('PASS authenticated download authorization, SHA-256/size and parsed Word contents');
console.log(`Observed statuses: ${[...observed].join(' -> ')}. Synthetic case: ${item.id}`);
writeFileSync(new URL('../../infrastructure/local/generated/document-demo.json',import.meta.url),JSON.stringify({caseId:item.id,jobId:job.jobId,tenantId:fixture.acmeId}));
