import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {client,signIn} from './oidc-session.mjs';
const fixture=JSON.parse(readFileSync(new URL('../../infrastructure/local/generated/demo-ids.json',import.meta.url),'utf8'));
const tokens={},api={};
for(const name of ['admin','requester','manager','finance','auditor','outsider']) {tokens[name]=await signIn(name);api[name]=client(tokens[name]);}
const path=`/tenants/${fixture.acmeId}/cases`;
const tenant=`/tenants/${fixture.acmeId}`;
const purchase={vendor:'Synthetic Equipment Supply',description:'Video editing laptop',currency:'USD',costCenter:'CREATIVE-01',justification:'Edit training videos',lineItems:[{description:'Laptop',quantity:'1',unitPrice:'4200.00'}]};
const body={purchase,workflowId:fixture.workflowId};
const key=crypto.randomUUID();
let item=await api.requester(path,{method:'POST',body,key});
assert.deepEqual(await api.requester(path,{method:'POST',body,key}),item);
await api.requester(path,{method:'POST',body:{...body,purchase:{...purchase,vendor:'Changed'}},key,expected:409});
console.log('PASS command replay and mismatched-body conflict');
await api.outsider(`${path}/${item.id}`,{expected:404});
await api.manager(`${path}/${item.id}`,{expected:404});
await api.auditor(path,{method:'POST',body,expected:403});
await api.requester(path,{method:'POST',body:{...body,workflowId:crypto.randomUUID()},expected:404});
await api.requester(`${path}/${item.id}/assignments`,{method:'PUT',body:{expectedVersion:item.version,approverIds:[fixture.users.requester,fixture.users.finance]},expected:400});
console.log('PASS cross-tenant, unassigned reviewer, auditor, foreign workflow and self-approval denials');
const stale=item.version;
item=await api.requester(`${path}/${item.id}`,{method:'PUT',body:{...body,expectedVersion:stale}});
await api.requester(`${path}/${item.id}`,{method:'PUT',body:{...body,expectedVersion:stale},expected:409});
await api.requester(`${path}/${item.id}/start`,{method:'POST',body:{expectedVersion:item.version},expected:400});
item=await api.requester(`${path}/${item.id}/assignments`,{method:'PUT',body:{expectedVersion:item.version,approverIds:[fixture.users.manager,fixture.users.finance]}});
item=await api.requester(`${path}/${item.id}/start`,{method:'POST',body:{expectedVersion:item.version}});
assert.equal(item.state,'ACTIVE');
await api.requester(`${path}/${item.id}`,{method:'PUT',body:{...body,expectedVersion:item.version},expected:409});
await api.finance(`${path}/${item.id}/actions`,{method:'POST',body:{expectedVersion:item.version,action:'APPROVE'},expected:403});
const firstKey=crypto.randomUUID();const firstBody={expectedVersion:item.version,action:'APPROVE'};
item=await api.manager(`${path}/${item.id}/actions`,{method:'POST',body:firstBody,key:firstKey});
assert.equal(item.state,'ACTIVE');
assert.deepEqual(await api.manager(`${path}/${item.id}/actions`,{method:'POST',body:firstBody,key:firstKey}),item);
console.log('PASS optimistic concurrency, start validation, input immutability, ordered approval and replay');
const approveVersion=item.version;
const outcomes=await Promise.all([1,2].map(async()=>{
  const result=await fetch(`http://127.0.0.1:8080/api/v1${path}/${item.id}/actions`,{method:'POST',headers:{Authorization:`Bearer ${tokens.finance}`,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({expectedVersion:approveVersion,action:'APPROVE'})});
  return result.status;
}));
assert.deepEqual(outcomes.sort(),[200,409]);
item=await api.requester(`${path}/${item.id}`);
assert.equal(item.state,'APPROVED');assert.equal(item.documentStatus,'QUEUED');
const audit=await api.auditor(`${path}/${item.id}/audit`);
assert.equal(audit.items.filter(a=>a.eventType==='CASE_APPROVE').length,2);
console.log('PASS concurrent final approval produces one successful transition and two total approval audit events');
let draft=await api.requester(path,{method:'POST',body});
draft=await api.requester(`${path}/${draft.id}/actions`,{method:'POST',body:{expectedVersion:draft.version,action:'CANCEL'}});
await api.requester(`${path}/${draft.id}`,{method:'PUT',body:{...body,expectedVersion:draft.version},expected:409});
const corrected=await api.requester(path,{method:'POST',body:{...body,originalCaseId:draft.id}});
assert.equal(corrected.originalCaseId,draft.id);
const firstPage=await api.requester(`${path}?limit=1`);assert.equal(firstPage.items.length,1);assert.ok(firstPage.nextCursor);
const inserted=await api.requester(path,{method:'POST',body});
const secondPage=await api.requester(`${path}?limit=100&cursor=${firstPage.nextCursor}`);
assert.ok(!secondPage.items.some(c=>c.id===firstPage.items[0].id||c.id===inserted.id));
console.log('PASS terminal cancellation, linked correction and keyset pagination under insertion');
let members=(await api.admin(tenant+'/memberships')).items;
const requester=members.find(m=>m.userId===fixture.users.requester);
try {
  const revoked=await api.admin(tenant+'/memberships',{method:'PUT',body:{userId:requester.userId,roles:requester.roles,active:false,expectedVersion:requester.version}});
  await api.requester(path,{method:'POST',body,key,expected:404});
  await api.requester(`${path}/${item.id}`,{expected:404});
  console.log('PASS membership revocation denies new reads and cached command replay');
} finally {
  members=(await api.admin(tenant+'/memberships')).items;
  const current=members.find(m=>m.userId===requester.userId);
  await api.admin(tenant+'/memberships',{method:'PUT',body:{userId:current.userId,roles:requester.roles,active:true,expectedVersion:current.version}});
}
const unauthenticated=await fetch(`http://127.0.0.1:8080/api/v1/me`);assert.equal(unauthenticated.status,401);
const broken=await fetch('http://127.0.0.1:8080/api/v1/me',{headers:{Authorization:'Bearer invalid'}});assert.equal(broken.status,401);
console.log('PASS missing and malformed bearer tokens rejected');
console.log('Purchase API suite passed against real PostgreSQL and Keycloak. Document execution is not part of this suite.');
